# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Ninja
        run: choco install ninja
      
      - name: Install MinGW
        run: choco install mingw
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.2
        with:
          host: windows
          arch: win64_mingw81

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          mkdir release
          cd release
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc ..
          cmake --build . --target all
